# template for server

# Требуется доработка.
# Этот файл не берется Спрингом
# Приложение с профилем Прод все равно стартует с настройками
# из application.yaml, то есть на порту 8080

app:
  host-url: http://localhost:8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jira
    username: jira
    password: JiraRush
  server:
    port: 8081

